modLoader="javafml" #mandatory
loaderVersion="[2,)" #mandatory
license="MIT"
issueTrackerURL = "https://github.com/matthewperiut/Chisel-Reborn/issues"

[[mods]]
modId = "lovelycrops"
version = "${version}"
displayName = "Lovely Crops"
authors = ["Slainlight"]
description = '''
Adds Grapes and Corn to Minecraft!
'''
logoFile = "assets/lovelycrops/icon.png"

[[dependencies.lovelycrops]]
modId="minecraft"
type="required"
versionRange="[1.20,4]"

[[dependencies.lovelycrops]]
modId="neoforge"
type="required"
versionRange="[0,)"

[[dependencies.lovelycrops]]
modId="architectury"
type="required"
versionRange="[0,)"